# @package _global_
defaults:
 - override /data: spatial2D
 - override /system: spatial2D

# --- Training Run / Checkpoint ---
run_folder_path: /insomnia001/depts/iicd/users/kz2537/viaABC/run/train/spatial2D/2026-05-07_14-19-08_bs10_acc2_nw2
checkpoint_substr: last

# --- System Overrides ---
system:
  pooling_method: no_cls

# --- viaABC Parameters ---
abc:
  num_particles: 100
  k: 5
  q_threshold: 0.999
  max_generations: 20
  num_workers: 64
  simulation_batch_size: 4
  max_pending_simulations: 16

# --- Output Folder ---
folder_name: ${run_folder_path}/inference_output
